version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - build: babel src --out-dir dist --delete-dir-on-start
      - test: babel test-es6 --out-dir test --delete-dir-on-start && mocha
